# Generated by Django 4.2.5 on 2023-09-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopingcart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update',
            new_name='updated',
        ),
    ]
